### ISSUE TITLE
Crash on start - Unsupported PipeWire object type PipeWire:Interface:SecurityContext

### ISSUE THREAD

**Issue by pallaswept** [dimtpap/coppwr#17]
**System information**
- **coppwr** version (See in Help → About): git main head, 6dc4adf
- **coppwr** installation method (Flathub, AUR, .deb, .rpm): rpm
- **PipeWire** version (See with `pipewire --version`): git master
- OS: OpenSUSE Tumbleweed
- Desktop environment/Window manager: KDE Plasma

**Describe the bug**
coppwr which was previously working, crashes on start. I briefly see a flash of the UI, then the following error.

```
> RUST_BACKTRACE=1 coppwr 
Error binding object 3: Unsupported PipeWire object type PipeWire:Interface:SecurityContext
thread '<unnamed>' panicked at /home/abuild/rpmbuild/BUILD/coppwr-1.6.0+git20241018.8eb9e41/vendor/libspa-0.8.0/src/pod/deserialize.rs:1002:9:
Not all fields have been deserialized from the struct
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: libspa::pod::deserialize::PodDeserializer::deserialize_from
   3: coppwr::backend::bind::listeners::profiler::{{closure}}
   4: pipewire::profiler::ProfilerListenerLocalBuilder::register::profiler_events_profile
   5: profiler_proxy_demarshal_profile
   6: process_remote
   7: on_remote_data
   8: loop_iterate
   9: pw_main_loop_run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at library/core/src/panicking.rs:221:5:
panic in a function that cannot unwind
stack backtrace:
   0:     0x563194b7faba - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h500272b372dbee0d
   1:     0x5631948aec2b - core::fmt::write::h7d5f1514cee5490d
   2:     0x563194b615ce - std::io::Write::write_fmt::h79aafa4f92dbd990
   3:     0x563194b5a122 - std::panicking::default_hook::{{closure}}::h3be5635ee55fbe2b
   4:     0x563194b5aef3 - std::panicking::rust_panic_with_hook::hbb6bc5e5dcf363de
   5:     0x563194b805f2 - std::panicking::begin_panic_handler::{{closure}}::he8c824647d733ff6
   6:     0x563194b80589 - std::sys::backtrace::__rust_end_short_backtrace::h9ef7b92757e5bdf6
   7:     0x563194b5a524 - rust_begin_unwind
   8:     0x5631946280d4 - core::panicking::panic_nounwind_fmt::h083a40dda093f096
   9:     0x563194628135 - core::panicking::panic_nounwind::h643673e2f32c1c91
  10:     0x5631946280f0 - core::panicking::panic_cannot_unwind::h6febb514fee19e5b
  11:     0x563194ae3e00 - pipewire::profiler::ProfilerListenerLocalBuilder::register::profiler_events_profile::h423f253dfcc57d90
  12:     0x7fb9c5b4f58d - profiler_proxy_demarshal_profile
  13:     0x7fb9c62315b6 - process_remote
  14:     0x7fb9c6231c48 - on_remote_data
  15:     0x7fb9c723b186 - loop_iterate
  16:     0x7fb9c71b6abe - pw_main_loop_run
  17:     0x563194666be8 - std::sys::backtrace::__rust_begin_short_backtrace::h30162f6776a32d83
  18:     0x5631946b4cca - core::ops::function::FnOnce::call_once{{vtable.shim}}::hb2d056a0a9e8be28
  19:     0x563194b6786b - std::sys::pal::unix::thread::Thread::new::thread_start::h0ff12e413e9f52ad
  20:     0x7fb9c6e983b2 - start_thread
  21:     0x7fb9c6f1d5fc - __clone3
  22:                0x0 - <unknown>
thread caused non-unwinding panic. aborting.
Aborted (core dumped)

```

**To Reproduce**
1. run coppwr
2. Crash

**Expected behavior**
coppwr being cool.

**Additional context**
I build coppwr and pipewire from git sources. Pipewire is usually updated quite frequently, nearly every day. coppwr gets an update occasionally as my rust vendoring takes a little more manual input. 
Until recently, this same build of coppwr has been working well here, I most recently was using it a week or two ago. Today when I tried to use it, I got this crash. 
Originally, this was with coppwr built from commit 6dc4adf . Updated the coppwr build to the latest head here, 8eb9e41 , same behaviour.

Thanks again for this awesome tool. If there's anything I can do to help with this bug let me know.

**Comment by dimtpap** [comment]
Since https://github.com/PipeWire/pipewire/commit/fa1ec61cf0b1e8c07304241309c3ee5ba9268e5b there are new data that PipeWire sends for profiling, I haven't updated coppwr to handle it
